---
- hosts: localhost
  connection: local
  become: true
  vars:
    - plex_install_package: 'https://downloads.plex.tv/plex-media-server/{{ plex_version }}/plexmediaserver_{{ plex_version }}_amd64.deb'
  tasks:
    - name: Updating APT-CACHE
      apt:
        update_cache: yes

    - name: Installing ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installing Plex Pre-Reqs
      apt:
        name: "{{ item }}"
        state: "present"
        install_recommends: no
      with_items:
        - 'avahi-daemon'
        - 'avahi-utils'
        - 'cifs-utils'
        - 'libavahi-client3'
        - 'libavahi-common3'
        - 'libavahi-common3'
        - 'libavahi-core7'
        - 'libdaemon0'
        - 'libnss-mdns'

    - name: Installing Plex
      apt:
        deb: "{{ plex_install_package }}"
        state: "present"
        install_recommends: no
