version: '2'
services:
  plex:
    build: ./
    image: plex
    volumes:
      - "plex_config:/config"
      - "/mnt/movies:/movies"
      - "/mnt/music:/music"
      - "/mnt/pictures:/pictures"
      - "/mnt/tv_shows:/tv_shows"
    ports:
      - "1900:1900/udp"
      - "5353:5353/udp"
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
    restart: always

volumes:
  plex_config:
